// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    Animation: typeof import('./src/components/Animation.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    Footer: typeof import('./src/components/modal/Footer.vue')['default']
    GeekTransition: typeof import('./src/components/GeekTransition.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    Modal: typeof import('./src/components/modal/Modal.vue')['default']
    Rate: typeof import('./src/components/Rate.vue')['default']
    TodoList: typeof import('./src/components/TodoList.vue')['default']
    TodoListPinia: typeof import('./src/components/TodoListPinia.vue')['default']
    Transition: typeof import('./src/components/Transition.vue')['default']
  }
}

export { }
